name: Finance-Management-Pipeline

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      mysql_security:
        image: mysql:latest
        ports:
          - 3333:3306
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: finance_management_security

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven

    - name: Build Events Package
      run: mvn -Dmaven.repo.local=$HOME/.m2/repository clean package -f ./events/pom.xml

    - name: Run Tests for Security Service
      working-directory: ./Services/security
      run: mvn -Dmaven.repo.local=$HOME/.m2/repository clean test
