name: Finance-Management-Pipeline

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      mysql_security:
        image: mysql:latest
        ports:
          - 3333:3306
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: finance_management_security

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Cache Maven Dependencies
      uses: actions/cache@v4
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven

    - name: Build Events Package
      working-directory: ./events
      run: mvn clean install

    - name: Verify Events Installation
      run: ls -R ~/.m2/repository/com/finance_management/events

    - name: Run Security Microservice Tests
      working-directory: ./Services/security
      run: mvn -U test
